exclude: "migrations|.git|.venv"
default_stages: [commit]
fail_fast: true

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: mixed-line-ending

  - repo: https://github.com/psf/black
    rev: 23.12.0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args: [--resolve-all-configs, --skip-gitignore]

  - repo: local
    hooks:
      - id: pylint
        name: pylint
        entry: |
          env DATABASE_URL="postgres://blank:blank@127.0.0.1:5432/blank"
          python -m pylint
        language: system
        types: [python]

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        args: ["--config=setup.cfg"]
        additional_dependencies:
          - flake8-bugbear==23.12.2
          - flake8-no-pep420==2.7.0
          - flake8-print==5.0.0
          - flake8-logging==1.4.0

  - repo: https://github.com/rtts/djhtml
    rev: 3.0.6
    hooks:
      - id: djhtml
        entry: djhtml -t 2

  - repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.340
    hooks:
      - id: pyright
        entry: python -m pyright

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py310-plus]

  - repo: https://github.com/jazzband/pip-tools
    rev: 7.3.0
    hooks:
      - id: pip-compile
        name: pip-compile rasa_actions
        args: [requirements/rasa_actions/requirements.in]
        files: ^requirements/rasa_actions/requirements\.(in|txt)$
      - id: pip-compile
        name: pip-compile site local
        args: [requirements/site/local.in]
        files: ^requirements/site/(base|local)\.(in|txt)$
      - id: pip-compile
        name: pip-compile local
        args: [requirements/local/requirements.in]
        files: ^requirements/(local|rasa_actions|site)/(requirements|base|local)\.(in|txt)$
