version: "3"

volumes:
  poke_postgres_data: {}

services:
  rasa:
    image: rasa/rasa:3.5.17-full
    ports:
      - "5005:5005"
    volumes:
      - ./poke_bot:/app:z
    command:
      - run
      - --enable-api
      - --cors
      - "*"
    env_file:
      - ./.envs/.postgres
    depends_on:
      - django
      - postgres

  rasa_actions:
    build:
      context: .
      dockerfile: ./compose/rasa_actions/Dockerfile
    ports:
      - "5055:5055"
    volumes:
      - ./poke_bot/actions:/app/actions:z
    depends_on:
      - rasa

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: poke_django
    container_name: poke_django
    depends_on:
      - postgres
    volumes:
      - ./site:/app:z
    env_file:
      - ./.envs/.django
      - ./.envs/.postgres
    ports:
      - "8000:8000"
    command: /start

  postgres:
    image: postgres:16-bookworm
    ports:
      - "5432:5432"
    env_file:
      - ./.envs/.postgres
