[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true


[tool.pyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.10"
exclude = [".venv", "**/migrations"]
include = ["app"]


[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
skip = [".venv/", ".git/", ".rasa", "**/migrations"]
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
