[tool.black]
line-length = 120
target-version = ["py310"]
skip-string-normalization = true

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
skip = [
    "venv/",
    ".venv/",
    ".git/",
    ".rasa"
]
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
